// <auto-generated />
using System;
using HOP_CFP_Backend.Library.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HDP_CFP_Backend.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260402103617_Tim_20260402_2")]
    partial class Tim_20260402_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.KeyValueSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Group", "Key");

                    b.ToTable("KeyValueSetting");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.Manager.AdminFunction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("ActionFunctionSN")
                        .HasColumnType("smallint");

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.HasKey("Id");

                    b.ToTable("AdminFunction");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.Manager.AdminMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("AdminFunctionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminMenu");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.Manager.AdminMenuByRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("ActionFunctionAssembly")
                        .HasColumnType("int");

                    b.Property<Guid>("AdminMenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.HasKey("Id");

                    b.ToTable("AdminMenuByRole");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.Manager.Log_ManagerLogin", b =>
                {
                    b.Property<short>("ActionType")
                        .HasColumnType("smallint")
                        .HasComment("(1)登入 (2)登出");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("IsLogout")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.ToTable("Log_ManagerLogin");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.Manager.Log_ManagerLoginFail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.HasKey("Id");

                    b.ToTable("Log_ManagerLoginFail");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.Manager.Log_ManagerWatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.Property<Guid?>("WatchingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Log_ManagerWatch");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.Manager.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("帳號");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Email");

                    b.Property<bool>("EmailConfirm")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastPasswordChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("使用者名稱");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)")
                        .HasComment("密碼");

                    b.Property<DateTime?>("PauseDate")
                        .HasColumnType("datetime2")
                        .HasComment("停權時間");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<string>("TaxID")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("統編");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.HasKey("Id");

                    b.HasIndex("TaxID");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.Manager.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("角色名稱");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.HasKey("Id");

                    b.HasIndex("UpdateDate");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.ManyToMany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Params")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelationType")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceTable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetTable")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.HasKey("Id");

                    b.HasIndex("TargetId");

                    b.HasIndex("SourceId", "TargetTable", "RelationType");

                    b.ToTable("ManyToMany");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("料號");

                    b.Property<string>("ProductModel")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("產品型號");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("產品名稱");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.HasKey("Id");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.MaterialCompare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("供應商料號");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("SupplierId");

                    b.ToTable("MaterialCompare");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.MaterialGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("群組代號");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("群組名稱");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.HasKey("Id");

                    b.ToTable("MaterialGroup");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.MaterialNotify", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSend")
                        .HasColumnType("bit")
                        .HasComment("是否發送");

                    b.Property<bool>("IsUpdate")
                        .HasColumnType("bit")
                        .HasComment("是否更新資料");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.HasKey("Id");

                    b.ToTable("MaterialNotify");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.MaterialSpec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MaterialCompareId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("名稱");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SpecNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("規格編號");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.HasKey("Id");

                    b.HasIndex("MaterialCompareId");

                    b.ToTable("MaterialSpec");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("聯絡窗口");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("聯絡電話");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Email");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("名稱");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<string>("TaxID")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("統編");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.HasKey("Id");

                    b.HasIndex("TaxID");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.System.DataChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<short>("Action")
                        .HasColumnType("smallint")
                        .HasComment("(0)新增 (1)編輯 (2)刪除");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DifferenceJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimaryKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.HasKey("Id");

                    b.ToTable("DataChange");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.System.Log_BackendPageRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LoadTime")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueryString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.HasKey("Id");

                    b.ToTable("Log_BackendPageRequest");
                });

            modelBuilder.Entity("HOP_CFP_Backend.Library.Models.System.SysConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasComment("狀態");

                    b.Property<string>("TypeName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasComment("更新時間");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("修改人員");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SysConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
